# Generated by Django 6.0.3 on 2026-04-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0003_category_description_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='category_image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
